# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-19 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='documento',
            field=models.BigIntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.BigIntegerField(max_length=12),
        ),
    ]
