# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-08-19 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20200819_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='documento',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.BigIntegerField(),
        ),
    ]
